#!/bin/bash

TBB_START_PROG="$(grep '^X-JonDoBrowser-ExecShell' $1 | tail -1 | sed 's/^X-JonDoBrowser-ExecShell=//' | sed 's/%.//')"

shift

if [ "$#" -ge 1 ]
then
  echo "Launching '${TBB_START_PROG} $@'..."
else
  echo "Launching '${TBB_START_PROG}'..."
fi

eval "${TBB_START_PROG} $@"
